"""Documentation Agent — generates README.md for the target project."""

import json
import logging
from typing import Any

from database.chroma_db import log_to_db
from services.file_service import write_file
from services.llm_service import call_model

logger = logging.getLogger(__name__)

_SYS = "You are a technical writer. Generate a clear, professional README.md in Markdown. Be concise but complete."


def _ascii_diagram(bp: dict) -> str:
    routes = bp.get("routes", [])
    tables = [t.get("name", "tbl") for t in bp.get("db_tables", [])]
    route_lines = "\n".join(
        f"│  {r.get('method', 'GET'):6} {r.get('path', '/'):<30} → {r.get('description', '')}" for r in routes[:8]
    )
    table_str = " │ ".join(tables)
    return (
        "┌──────────────────────────────────────────────┐\n"
        "│   Streamlit Frontend   (port 8501)           │\n"
        "└──────────────────┬───────────────────────────┘\n"
        "                   │ HTTP / requests\n"
        "                   ▼\n"
        "┌──────────────────────────────────────────────┐\n"
        "│   FastAPI Backend      (port 5000)           │\n"
        f"{route_lines}\n"
        "└──────────────────┬───────────────────────────┘\n"
        "                   │ SQLAlchemy ORM\n"
        "                   ▼\n"
        "┌──────────────────────────────────────────────┐\n"
        "│   SQLite Database                            │\n"
        f"│   {table_str}\n"
        "└──────────────────────────────────────────────┘"
    )


def _fallback(req: dict, bp: dict, files: list[str]) -> str:
    pn = req.get("project_name", "Generated Project")
    feature_md = "\n".join(f"- {f}" for f in req.get("features", []))
    route_md = "\n".join(
        f"| {r.get('method')} | `{r.get('path')}` | {r.get('description')} |" for r in bp.get("routes", [])
    )
    table_md = "\n".join(f"| {t.get('name')} | {', '.join(t.get('columns', []))} |" for t in bp.get("db_tables", []))
    files_md = "\n".join(f"- `{f}`" for f in files)
    diagram = _ascii_diagram(bp)
    return (
        f"# {pn}\n"
        "> Generated by **ProjectPilot**\n\n"
        f"## Features\n{feature_md}\n\n"
        "## Tech Stack\n"
        "| Layer | Technology |\n|-------|------------|\n"
        "| Backend | FastAPI + Uvicorn |\n| Frontend | Streamlit |\n"
        "| Database | SQLite + SQLAlchemy |\n| Language | Python 3.11 |\n\n"
        "## Architecture\n```\n" + diagram + "\n```\n\n"
        "## Quick Start\n```bash\npip install -r requirements.txt\n"
        "uvicorn backend.main:app --port 5000 --reload\n"
        "streamlit run frontend/app.py\n```\n\n"
        "## Docker\n```bash\ndocker-compose up --build\n```\n\n"
        f"## API Routes\n| Method | Endpoint | Description |\n|--------|----------|-------------|\n{route_md}\n\n"
        f"## Database\n| Table | Columns |\n|-------|--------|\n{table_md}\n\n"
        f"## Generated Files\n{files_md}\n\n"
        "## License\nMIT\n"
    )


def run(
    requirements: dict[str, Any],
    blueprint: dict[str, Any],
    generated_files: list[str],
    job_id: str,
    model: str = None,
) -> str:
    log_to_db(job_id, "DocsAgent", "Generating README.md…")

    prompt = (
        f"Generate a complete README.md for: {requirements.get('project_name', 'App')}\n"
        f"Type: {requirements.get('project_type')}\n"
        f"Features: {', '.join(requirements.get('features', []))}\n"
        f"Routes: {json.dumps(blueprint.get('routes', [])[:6])}\n"
        f"Tables: {', '.join(t.get('name', '') for t in blueprint.get('db_tables', []))}\n"
        "Include: overview, features, tech stack, quick start, API docs, docker, usage."
    )
    try:
        readme = call_model(prompt, system_prompt=_SYS, model=model or "local")
        if len(readme) < 200:
            raise ValueError("README too short")
    except (RuntimeError, ValueError) as exc:
        log_to_db(job_id, "DocsAgent", f"LLM failed — using template: {exc}", "WARNING")
        readme = _fallback(requirements, blueprint, generated_files)

    # Inject ASCII diagram if not already present
    if "┌───" not in readme:
        diagram = _ascii_diagram(blueprint)
        lines = readme.split("\n")
        insert = next(
            (i for i, l in enumerate(lines) if l.startswith("## ") and i > 0),
            len(lines) // 2,
        )
        lines.insert(insert, f"\n## Architecture\n\n```\n{diagram}\n```\n")
        readme = "\n".join(lines)

    write_file(job_id, "README.md", readme)
    log_to_db(job_id, "DocsAgent", "README.md written.")
    return readme
