"""
Validation Agent — final quality gate before packaging.

Runs after DocsAgent, before ZipService.  No LLM calls — all checks are
deterministic so results are reproducible and fast.

Hardcoded checks:
  1. Structural  — required files exist (main.py, requirements.txt, README.md)
  2. Syntax      — py_compile every .py file; reports each failure
  3. Test suite  — runs the pytest suite generated by TestGenAgent
  4. Report      — writes VALIDATION_REPORT.md into the project root

Returns a summary dict that gets logged to ChromaDB and stored in the job.
"""

import logging
import py_compile
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

from database.chroma_db import log_to_db
from services.file_service import BASE_DIR, write_file

logger = logging.getLogger(__name__)

#  Hardcoded required-file rules 
# Each entry: (glob_pattern, description)
# At least one file matching the pattern must exist.
REQUIRED_FILES: List[Tuple[str, str]] = [
    ("requirements.txt",         "Python dependencies"),
    ("README.md",                "Project documentation"),
    ("backend/main.py",          "FastAPI/Flask entry point"),
    ("**/__init__.py",           "Package init files"),
]

# Directories that, if present, must contain at least one test file
TEST_DIR_NAMES = ["tests", "test"]


def run(
    job_id: str,
    requirements: Dict[str, Any],
    blueprint: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Execute all validation checks and write VALIDATION_REPORT.md.
    Returns a summary dict; never raises — failures are captured, not propagated.
    """
    log_to_db(job_id, "ValidationAgent", "Starting validation…")
    t_start = time.monotonic()

    job_dir = BASE_DIR / job_id
    if not job_dir.exists():
        msg = f"Job directory not found: {job_dir}"
        log_to_db(job_id, "ValidationAgent", msg, "ERROR")
        return {"passed": False, "error": msg}

    #  Run each check 
    structural = _check_structure(job_dir, requirements, blueprint)
    syntax     = _check_syntax(job_dir)
    tests      = _run_tests(job_dir, job_id)

    elapsed_ms = int((time.monotonic() - t_start) * 1000)

    #  Compute overall pass/fail 
    syntax_ok     = all(r["valid"] for r in syntax.values())
    structure_ok  = all(r["found"] for r in structural.values())
    tests_ok      = tests.get("passed", False)
    tests_skipped = tests.get("skipped", False)

    # Overall: pass if structure + syntax are clean; test failures are warnings
    overall_passed = structure_ok and syntax_ok

    summary = {
        "passed":          overall_passed,
        "structure_ok":    structure_ok,
        "syntax_ok":       syntax_ok,
        "tests_ok":        tests_ok,
        "tests_skipped":   tests_skipped,
        "total_py_files":  len(syntax),
        "syntax_errors":   [k for k, v in syntax.items() if not v["valid"]],
        "missing_files":   [k for k, v in structural.items() if not v["found"]],
        "elapsed_ms":      elapsed_ms,
    }

    #  Write the markdown report 
    report_md = _build_report(summary, structural, syntax, tests, requirements)
    write_file(job_id, "VALIDATION_REPORT.md", report_md)

    status_icon = " PASSED" if overall_passed else " FAILED"
    log_to_db(
        job_id, "ValidationAgent",
        f"Validation {status_icon} — "
        f"syntax:{syntax_ok} structure:{structure_ok} tests:{tests_ok} "
        f"({elapsed_ms}ms)"
    )
    return summary


#  Check helpers 

def _check_structure(
    job_dir: Path,
    requirements: Dict[str, Any],
    blueprint: Dict[str, Any],
) -> Dict[str, Dict]:
    """Verify hardcoded required files plus blueprint-derived files."""
    results: Dict[str, Dict] = {}

    # Static required files
    for pattern, description in REQUIRED_FILES:
        found = bool(list(job_dir.glob(pattern)))
        results[pattern] = {"description": description, "found": found}

    # Dynamic: every route in the blueprint should have a corresponding .py
    for route in blueprint.get("routes", []):
        module = route.get("module", "")
        if module and module.endswith(".py"):
            found = (job_dir / module).exists()
            results[module] = {"description": f"Route module for {route.get('path','?')}", "found": found}

    return results


def _check_syntax(job_dir: Path) -> Dict[str, Dict]:
    """Run py_compile on every .py file; return per-file results."""
    results: Dict[str, Dict] = {}
    py_files = sorted(job_dir.rglob("*.py"))

    for py_file in py_files:
        rel = str(py_file.relative_to(job_dir))
        try:
            py_compile.compile(str(py_file), doraise=True)
            results[rel] = {"valid": True, "error": None}
        except py_compile.PyCompileError as exc:
            results[rel] = {"valid": False, "error": str(exc)}
        except Exception as exc:
            results[rel] = {"valid": False, "error": f"Unexpected: {exc}"}

    return results


def _run_tests(job_dir: Path, job_id: str) -> Dict[str, Any]:
    """Run pytest inside the job directory. Return a result dict."""
    # Locate test directory
    test_dir = None
    for name in TEST_DIR_NAMES:
        candidate = job_dir / name
        if candidate.exists() and any(candidate.rglob("test_*.py")):
            test_dir = candidate
            break

    if test_dir is None:
        return {"passed": False, "skipped": True, "output": "No test directory found.", "failures": []}

    try:
        result = subprocess.run(
            ["python", "-m", "pytest", str(test_dir), "-v", "--tb=short", "--no-header", "-q"],
            capture_output=True,
            text=True,
            timeout=60,
            cwd=str(job_dir),
        )
        output = result.stdout + result.stderr
        passed = result.returncode == 0
        failures = _parse_failures(output)
        return {
            "passed":   passed,
            "skipped":  False,
            "output":   output[:4000],   # cap to 4k chars for storage
            "failures": failures,
        }
    except subprocess.TimeoutExpired:
        return {"passed": False, "skipped": False, "output": "pytest timed out (>60s).", "failures": []}
    except FileNotFoundError:
        return {"passed": False, "skipped": True, "output": "pytest not installed in this environment.", "failures": []}
    except Exception as exc:
        return {"passed": False, "skipped": False, "output": str(exc), "failures": []}


def _parse_failures(output: str) -> List[Dict[str, Any]]:
    import re
    failures = []
    for m in re.finditer(r"FAILED (.+?) - (.+)", output):
        failures.append({"test": m.group(1).strip(), "reason": m.group(2).strip()})
    return failures


#  Report builder 

def _build_report(
    summary: Dict[str, Any],
    structural: Dict[str, Dict],
    syntax: Dict[str, Dict],
    tests: Dict[str, Any],
    requirements: Dict[str, Any],
) -> str:
    now = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    project_name = requirements.get("project_name", "Project")

    overall = " PASSED" if summary["passed"] else " FAILED"
    test_icon  = "" if summary["tests_ok"] else (" skipped" if summary["tests_skipped"] else "")
    syn_icon   = "" if summary["syntax_ok"] else ""
    struct_icon = "" if summary["structure_ok"] else ""

    lines = [
        f"# Validation Report — {project_name}",
        f"",
        f"> Generated by **ProjectPilot ValidationAgent** · {now}",
        f"",
        f"## Overall: {overall}",
        f"",
        f"| Check | Result |",
        f"|-------|--------|",
        f"|  Structure | {struct_icon} |",
        f"|  Syntax    | {syn_icon} ({summary['total_py_files']} files) |",
        f"|  Tests     | {test_icon} |",
        f"|  Duration  | {summary['elapsed_ms']} ms |",
        f"",
    ]

    #  Structure section 
    lines += ["##  Structure Checks", ""]
    lines += ["| File / Pattern | Description | Status |", "|---|---|---|"]
    for pattern, info in structural.items():
        icon = "" if info["found"] else " MISSING"
        lines.append(f"| `{pattern}` | {info['description']} | {icon} |")
    lines.append("")

    #  Syntax section 
    lines += ["##  Syntax Validation", ""]
    errors = {k: v for k, v in syntax.items() if not v["valid"]}
    if not errors:
        lines.append(f"All {len(syntax)} Python files passed syntax check. ")
    else:
        lines.append(f"**{len(errors)} file(s) have syntax errors:**")
        lines.append("")
        for path, info in errors.items():
            lines += [f"### `{path}`", f"```", f"{info['error']}", f"```", ""]
    lines.append("")

    #  Test section 
    lines += ["##  Test Results", ""]
    if tests.get("skipped"):
        lines.append(f">  Tests skipped: {tests.get('output', '')}")
    else:
        status = " All tests passed" if tests.get("passed") else " Some tests failed"
        lines.append(f"**{status}**")
        failures = tests.get("failures", [])
        if failures:
            lines += ["", "**Failures:**", ""]
            for f in failures:
                lines.append(f"- `{f['test']}` — {f['reason']}")
        output_snippet = (tests.get("output") or "")[:1500]
        if output_snippet:
            lines += ["", "<details><summary>pytest output</summary>", "", "```", output_snippet, "```", "</details>"]
    lines.append("")

    #  Footer 
    missing = summary.get("missing_files", [])
    syn_errs = summary.get("syntax_errors", [])
    if missing or syn_errs:
        lines += ["##  Recommended Fixes", ""]
        for m in missing:
            lines.append(f"- Create missing file: `{m}`")
        for s in syn_errs:
            lines.append(f"- Fix syntax in: `{s}`")
        lines.append("")

    lines += [
        "---",
        "*ProjectPilot — ValidationAgent*",
    ]

    return "\n".join(lines)
